[package]
name = "sunfish"
version = "0.1.0"
authors = ["Recursing <buonanno.lorenzo@gmail.com>"]
edition = "2018"

[dependencies]
lru = "0.1.12"
lazy_static = "1.3.0"
rand = "0.6.5"
log = "0.4"
simplelog = "0.5"
jemallocator = "0.1.9"


[profile.test]
opt-level = 3